# To refresh existing project run `dipdup init --base --force` after modifying this file.
# To generate a new project from this replay run `dipdup new --replay <path_to_file>`.
#
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_blank
  package: tezos_domains
  version: 1.0.0
  description: Selective indexer for Tezos Domains smart contracts
  license: MIT
  name: Lev Gorodetskii
  email: dipdup@drsr.io
  postgres_image: postgres:15
  postgres_data_path: /var/lib/postgresql/data
  hasura_image: hasura/graphql-engine:v2.30.1
  line_length: 120
  package_manager: pdm
