# Run `dipdup new --replay configs/replay.yaml` to generate new project from this replay
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_blank
  package: tezos_domains
  version: 1.0.0
  description: Selective indexer for Tezos Domains smart contracts
  license: MIT
  name: Lev Gorodetskii
  email: dipdup@drsr.io
  postgresql_image: postgres:15
  hasura_image: hasura/graphql-engine:v2.30.1
  line_length: 120
